# version: "3.8"

# services:
#   app:
#     build:
#       context: .
#     env_file:
#       - .env  
#     ports: 
#       - "3000:3000"  
#     volumes:
#       - ./:/app
#       - /app/node_modules
#     restart: on-failure
#     command: >
#       sh -c "npm start"

#   db:
#     image: postgres
#     env_file: 
#       - .env
#     volumes:
#       - ./postgres_db:/data/db
#       - ./postgres-init.js:/docker-entrypoint-initdb.d/postgres-init.js:ro      

